beta-2の途中を追加
scouty-inc/holacracy_constitution pull request #11
Opened 2021-03-15 07:52 UTC by functionp

beta2

2021-03-31 07:39 UTC, r-takahama requested changes
特に自分が担当した2章について、そのままコピペされるはずではないつもりで書いたところを削除いただきたく、レビューコメントつけました

2021-03-31 07:39 UTC, r-takahama commented on holcracy_constitution_lapras.md
> +*組織*の他の*ロールリード*が自分の就いている*ロール*を代表して行動しているとき、あなたは*ロールリード*として彼らに対して次の義務を負います（※ロール名を名乗る件は消えた）。
```suggestion
*組織*の他の*ロールリード*が自分の就いている*ロール*を代表して行動しているとき、あなたは*ロールリード*として彼らに対して次の義務を負います。
```

2021-03-31 07:39 UTC, r-takahama commented on holcracy_constitution_lapras.md
> +- **(c) ドメインに影響を与える要求:** 他の人は、あなたの*ロール*のいずれかがコントロールしている*領域*に影響を与える許可を求めることができます。あなたは、あなたのロールの目的または責務を遂行する能力が低下する理由（※*反論*がこれに言い換えられた）が見つからない場合は、その影響を許可しなければなりません。もしそのような理由がある場合は、あなたはそれを要求者に説明しなければなりませ
```suggestion
- **(c) ドメインに影響を与える要求:** 他の人は、あなたの*ロール*のいずれかがコントロールしている*領域*に影響を与える許可を求めることができます。あなたは、あなたのロールの目的または責務を遂行する能力が低下する理由が見つからない場合は、その影響を許可しなければなりません。もしそのような理由がある場合は、あなたはそれを要求者に説明しなければなりません。
```

2021-03-31 07:39 UTC, r-takahama commented on holcracy_constitution_lapras.md
> +- **(c) サークルの優先順位:**（※新しい項目） あなたが何に取り組むかを選択するときは、あなたのロールが属するサークルもしくはそのいずれかのスーパーサークルの公式の*戦略*もしくは相対的な優先順位を考慮しなければなりません。公式の優先順位とは、*サークルリード*、もしくは、優先順位の衝突を解決し*サークル*の*戦略*を定義する権限をもつ*ロール*またはプロセスによって定義されたものです
```suggestion
- **(c) サークルの優先順位:** あなたが何に取り組むかを選択するときは、あなたのロールが属するサークルもしくはそのいずれかのスーパーサークルの公式の*戦略*もしくは相対的な優先順位を考慮しなければなりません。公式の優先順位とは、*サークルリード*、もしくは、優先順位の衝突を解決し*サークル*の*戦略*を定義する権限をもつ*ロール*またはプロセスによって定義されたものです。その上であなたは、あなたの個人的な優先順位やあなたが感じる*組織*の優先順位よりも、*組織*にとってこれらの公式の優先順位の方がより重要なものとして扱う必要があります。
```

2021-03-31 07:39 UTC, r-takahama commented on holcracy_constitution_lapras.md
> +- **(d) 期限:** *サークル*の*ガバナンス*、あるいは公式の*戦略*や優先順位付け（※ガバナンスに加えて追記）に、いつまでに何かをすることを指定する期限が含まれている場合、あなたは、必ずしもその期限を守る必要はありません。ただし、あなたは、その期限を期限を守るために必要なすべての行動が、そのサークルにおける他のあらゆる行動よりも優先度が高いという公式の優先順位付けとして解釈し、それに
```suggestion
- **(d) 期限:** *サークル*の*ガバナンス*、あるいは公式の*戦略*や優先順位付けに、いつまでに何かをすることを指定する期限が含まれている場合、あなたは、必ずしもその期限を守る必要はありません。ただし、あなたは、その期限を期限を守るために必要なすべての行動が、そのサークルにおける他のあらゆる行動よりも優先度が高いという公式の優先順位付けとして解釈し、それに応じて行動する必要があります。*サークル*における*ロール*間の優先順位の衝突を解決する権限を持つ*サークルリード*や別の*ロール*、またはプロセスは、この優先順位を無効にすることができます。
```

2021-03-31 07:41 UTC, functionp commented
> 特に自分が担当した2章について、そのままコピペされるはずではないつもりで書いたところを削除いただきたく、レビューコメントつけました

全部コミットしました

2021-04-06 15:58 UTC, nunukim approved these changes
5章の部分見ました。特に問題なさそうでした

2021-04-07 07:35 UTC, merged